project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left: 
      - text: Hands-on Exercise 
        menu: 
        - text: hands-on Exercise 1
          href: hands-on exercise 1/hands-on exercise 1.html
        - text: hands-on exercise 2 
          href: hands-on exercise 2/hands-on exercise 2.html
        - text: hands-on exercise 3 
          href: hands-on exercise 3/hands-on exercise 3.html
        - text: hands-on exercise 4 
          href: hands-on exercise 4/hands-on exercise 4.html
        - text: hands-on exercise 5 
          href: hands-on exercise 5/hands-on exercise 5.html
        - text: hands-on exercise 6 
          href: hands-on exercise 6/hands-on exercise 6.html
        - text: hands-on exercise 7 
          href: hands-on exercise 7/hands-on exercise 7.html
      - text: In-calss Exercise 
        menu: 
          - text: in-class exercise 1
            href: in-class exercise 1/in-class exercise 1.qmd
          - text: in-class exercise 2
            href: in-class exercise 2/in-class exercise 2.qmd 
          - text: in-class exercise 3
            href: in-class exercise 3/in-class exercise 3.qmd
          - text: in-class exercise 4
            href: in-class exercise 4/in-class exercise 4.qmd
          - text: in-class exercise 4
            href: in-class exercise 4/in-class exercise 4.qmd 
          - text: in-class exercise 5
            href: in-class exercise 5/in-class exercise 5.qmd 
          - text: in-class exercise 6
            href: in-class exercise 6/in-class exercise 6.qmd 
          - text: in-class exercise 7
            href: in-class exercise 7/in-class exercise 7.qmd 
      - text: Take-home Exercise 
        menu: 
          - text: take home exercise 1
            href: take home exercise 1/take home exercise 1.qmd
          - text: take home exercise 2
            href: take home exercise 2/take home exercise 2.qmd 
          - text: take home exercise 3
            href: take home exercise 3/take home exercise 3.qmd
          - text: take home exercise 4
            href: take home exercise 4/take home exercise 4.qmd
          - text: take home exercise 4
            href: take home exercise 4/take home exercise 4.qmd 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

