---
title: "Project"
author: "Xu Lin"
---

```{r}
pacman::p_load(lubridate, ggthemes, reactable,
reactablefmtr, gt, gtExtras, tidyverse, ggplot2)
```

```{r}
rental <- read_csv("data/rent.csv") 
```

```{r}
rentalnew <- rental %>%
  select(
    NoOfBedroom = `No of Bedroom`, 
    MonthlyRent = `Monthly Rent ($)`,
    ProjectName1 = `Project Name`,
    LeaseCommencementDate = `Lease Commencement Date`)
```

```{r}
postdistrictdata <- read_csv("data/realis2018.csv") %>%
  select(PlanningArea = "Planning Area",
         ProjectName2 = "Project Name") %>%
  distinct()
```

```{r}
Retentialdatamerged <- rentalnew %>%
  left_join(postdistrictdata, by = c("ProjectName1" = "ProjectName2")) %>%
  drop_na() %>%
  mutate(PlanningArea = case_when(
    PlanningArea == "YISHUN" ~ "Yishun",
    TRUE ~ PlanningArea 
  )) 
```

```{r}
Retentialdatamerged$LeaseCommencementDate <- as.Date(Retentialdatamerged$LeaseCommencementDate)
Retentialdatamerged$YearMonth <- format(Retentialdatamerged$LeaseCommencementDate, "%Y-%m")
rental_data <- Retentialdatamerged %>%
  filter(PlanningArea == "Jurong East", NoOfBedroom == 3)
```

```{r}
ggplot(rental_data, aes(x = YearMonth, y = MonthlyRent)) +
  geom_boxplot() +
  geom_smooth(method = "loess", colour = "blue", fill = "grey", alpha = 0.5, size = 1, aes(group = 1)) + 
  stat_summary(fun = median, geom = "line", colour = "red", size = 1, aes(group = 1)) +
  theme_minimal() +
  labs(title = "Monthly Rent for 3 Bedrooms in Jurong East",
       x = "Month by Year",
       y = "Monthly Rent $") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```







```{r}
stats_by_area_and_date <- Retentialdatamerged %>%
  group_by(PlanningArea, LeaseCommencementDate, NoOfBedroom) %>%
  summarise(
    MinRent = min(MonthlyRent, na.rm = TRUE),
    MaxRent = max(MonthlyRent, na.rm = TRUE),
    MedianRent = median(MonthlyRent, na.rm = TRUE),
    .groups = "drop" 
  )
```




























